[build]
  command = "vite build"
  publish = "dist"

[functions]
  external_node_modules = ["express", "multer", "@neondatabase/serverless"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
