[build]
  command = "npm run build"
  publish = "client/dist"
         
[functions]
  external_node_modules = ["express", "multer", [build]
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  external_node_modules = ["express", "multer", "@neondatabase/serverless"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
